# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

steps:
- task: Bash@3
  displayName: 'Build Temperature Observer'
  inputs:
    targetType: 'inline'
    script: |
      . $HOME/esp/esp-idf/export.sh

      idf.py build

- task: ArchiveFiles@2
  displayName: 'Archive full build folder'
  inputs:
    rootFolderOrFile: '$(Pipeline.Workspace)/s/build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/TemperatureObserver-$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: DownloadBuildArtifacts@1
  displayName: 'Download Zip File'
  inputs:
    itemPattern: '**/*.zip'
    downloadPath: '$(Build.ArtifactStagingDirectory)'